project_name: magic-home

release:
  github:
    owner: moonliightz
    name: magic-home

env:
  - GO111MODULE=on
  - GOPROXY=https://goproxy.io

before:
  hooks:
    - go mod download

builds:
  -
    main: ./cmd/main.go
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - freebsd
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64

archives:
  -
    replacements:
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

nfpms:
  -
    # You can change the name of the package.
    # This is parsed with the Go template engine and the following variables
    # are available:
    # - ProjectName
    # - Tag
    # - Version (Git tag without `v` prefix)
    # - Os
    # - Arch
    # - Arm (ARM version)
    # - Env (environment variables)
    # Default: `{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}`
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

    # Your app's vendor.
    # Default is empty.
    vendor: Patrick Stebbe

    # Your app's homepage.
    # Default is empty.
    homepage: https://github.com/MoonLiightz/magic-home

    # Your app's maintainer (probably you).
    # Default is empty.
    maintainer: Patrick Stebbe <info@moonliightz.de>

    # Your app's description.
    # Default is empty.
    description: A CLI and library written in Go for controlling Magic Home (Magic Hue) LED Strip Controllers.

    # Your app's license.
    # Default is empty.
    license: MIT

    # Formats to be generated.
    formats:
      - deb
      - rpm

    # Replacements for GOOS and GOARCH in the package name.
    # Keys should be valid GOOSs or GOARCHs.
    # Values are the respective replacements.
    # Default is empty.
    replacements:
      386: i386
      arm: armhf

  # Override default /usr/local/bin destination for binaries
  # bindir: /usr/bin
